using System.Collections.Generic;

namespace GcpClient.Runtime.Places.Utils
{
    public class DtoHelper
    {
        public static IReadOnlyDictionary<string, PlaceType> PlaceTypeTable = new Dictionary<string, PlaceType>()
        {
            { "accounting", PlaceType.Accounting },
            { "airport", PlaceType.Airport },
            { "amusement_park", PlaceType.Amusement_park },
            { "aquarium", PlaceType.Aquarium },
            { "art_gallery", PlaceType.Art_gallery },
            { "atm", PlaceType.Atm },
            { "bakery", PlaceType.Bakery },
            { "bank", PlaceType.Bank },
            { "bar", PlaceType.Bar },
            { "beauty_salon", PlaceType.Beauty_salon },
            { "bicycle_store", PlaceType.Bicycle_store },
            { "book_store", PlaceType.Book_store },
            { "bowling_alley", PlaceType.Bowling_alley },
            { "bus_station", PlaceType.Bus_station },
            { "cafe", PlaceType.Cafe },
            { "campground", PlaceType.Campground },
            { "car_dealer", PlaceType.Car_dealer },
            { "car_rental", PlaceType.Car_rental },
            { "car_repair", PlaceType.Car_repair },
            { "car_wash", PlaceType.Car_wash },
            { "casino", PlaceType.Casino },
            { "cemetery", PlaceType.Cemetery },
            { "church", PlaceType.Church },
            { "city_hall", PlaceType.City_hall },
            { "clothing_store", PlaceType.Clothing_store },
            { "convenience_store", PlaceType.Convenience_store },
            { "courthouse", PlaceType.Courthouse },
            { "dentist", PlaceType.Dentist },
            { "department_store", PlaceType.Department_store },
            { "doctor", PlaceType.Doctor },
            { "drugstore", PlaceType.Drugstore },
            { "electrician", PlaceType.Electrician },
            { "electronics_store", PlaceType.Electronics_store },
            { "embassy", PlaceType.Embassy },
            { "fire_station", PlaceType.Fire_station },
            { "florist", PlaceType.Florist },
            { "funeral_home", PlaceType.Funeral_home },
            { "furniture_store", PlaceType.Furniture_store },
            { "gas_station", PlaceType.Gas_station },
            { "gym", PlaceType.Gym },
            { "hair_care", PlaceType.Hair_care },
            { "hardware_store", PlaceType.Hardware_store },
            { "hindu_temple", PlaceType.Hindu_temple },
            { "home_goods_store", PlaceType.Home_goods_store },
            { "hospital", PlaceType.Hospital },
            { "insurance_agency", PlaceType.Insurance_agency },
            { "jewelry_store", PlaceType.Jewelry_store },
            { "laundry", PlaceType.Laundry },
            { "lawyer", PlaceType.Lawyer },
            { "library", PlaceType.Library },
            { "light_rail_station", PlaceType.Light_rail_station },
            { "liquor_store", PlaceType.Liquor_store },
            { "local_government_office", PlaceType.Local_government_office },
            { "locksmith", PlaceType.Locksmith },
            { "lodging", PlaceType.Lodging },
            { "meal_delivery", PlaceType.Meal_delivery },
            { "meal_takeaway", PlaceType.Meal_takeaway },
            { "mosque", PlaceType.Mosque },
            { "movie_rental", PlaceType.Movie_rental },
            { "movie_theater", PlaceType.Movie_theater },
            { "moving_company", PlaceType.Moving_company },
            { "museum", PlaceType.Museum },
            { "night_club", PlaceType.Night_club },
            { "painter", PlaceType.Painter },
            { "park", PlaceType.Park },
            { "parking", PlaceType.Parking },
            { "pet_store", PlaceType.Pet_store },
            { "pharmacy", PlaceType.Pharmacy },
            { "physiotherapist", PlaceType.Physiotherapist },
            { "plumber", PlaceType.Plumber },
            { "police", PlaceType.Police },
            { "post_office", PlaceType.Post_office },
            { "primary_school", PlaceType.Primary_school },
            { "real_estate_agency", PlaceType.Real_estate_agency },
            { "restaurant", PlaceType.Restaurant },
            { "roofing_contractor", PlaceType.Roofing_contractor },
            { "rv_park", PlaceType.Rv_park },
            { "school", PlaceType.School },
            { "secondary_school", PlaceType.Secondary_school },
            { "shoe_store", PlaceType.Shoe_store },
            { "shopping_mall", PlaceType.Shopping_mall },
            { "spa", PlaceType.Spa },
            { "stadium", PlaceType.Stadium },
            { "storage", PlaceType.Storage },
            { "store", PlaceType.Store },
            { "subway_station", PlaceType.Subway_station },
            { "supermarket", PlaceType.Supermarket },
            { "synagogue", PlaceType.Synagogue },
            { "taxi_stand", PlaceType.Taxi_stand },
            { "tourist_attraction", PlaceType.Tourist_attraction },
            { "train_station", PlaceType.Train_station },
            { "transit_station", PlaceType.Transit_station },
            { "travel_agency", PlaceType.Travel_agency },
            { "university", PlaceType.University },
            { "veterinary_care", PlaceType.Veterinary_care },
            { "zoo", PlaceType.Zoo },
        };

        public static IReadOnlyDictionary<string, ResponsePlaceType> PlaceTypeResponseTable = new Dictionary<string, ResponsePlaceType>
        {
            { "administrative_area_level_1", ResponsePlaceType.Administrative_area_level_1 },
            { "administrative_area_level_2", ResponsePlaceType.Administrative_area_level_2 },
            { "administrative_area_level_3", ResponsePlaceType.Administrative_area_level_3 },
            { "administrative_area_level_4", ResponsePlaceType.Administrative_area_level_4 },
            { "administrative_area_level_5", ResponsePlaceType.Administrative_area_level_5 },
            { "administrative_area_level_6", ResponsePlaceType.Administrative_area_level_6 },
            { "administrative_area_level_7", ResponsePlaceType.Administrative_area_level_7 },
            { "archipelago", ResponsePlaceType.Archipelago },
            { "colloquial_area", ResponsePlaceType.Colloquial_area },
            { "continent", ResponsePlaceType.Continent },
            { "country", ResponsePlaceType.Country },
            { "establishment", ResponsePlaceType.Establishment },
            { "finance", ResponsePlaceType.Finance },
            { "floor", ResponsePlaceType.Floor },
            { "food", ResponsePlaceType.Food },
            { "general_contractor", ResponsePlaceType.General_contractor },
            { "geocode", ResponsePlaceType.Geocode },
            { "health", ResponsePlaceType.Health },
            { "intersection", ResponsePlaceType.Intersection },
            { "landmark", ResponsePlaceType.Landmark },
            { "locality", ResponsePlaceType.Locality },
            { "natural_feature", ResponsePlaceType.Natural_feature },
            { "neighborhood", ResponsePlaceType.Neighborhood },
            { "place_of_worship", ResponsePlaceType.Place_of_worship },
            { "plus_code", ResponsePlaceType.Plus_code },
            { "point_of_interest", ResponsePlaceType.Point_of_interest },
            { "political", ResponsePlaceType.Political },
            { "post_box", ResponsePlaceType.Post_box },
            { "postal_code", ResponsePlaceType.Postal_code },
            { "postal_code_prefix", ResponsePlaceType.Postal_code_prefix },
            { "postal_code_suffix", ResponsePlaceType.Postal_code_suffix },
            { "postal_town", ResponsePlaceType.Postal_town },
            { "premise", ResponsePlaceType.Premise },
            { "room", ResponsePlaceType.Room },
            { "route", ResponsePlaceType.Route },
            { "street_address", ResponsePlaceType.Street_address },
            { "street_number", ResponsePlaceType.Street_number },
            { "sublocality", ResponsePlaceType.Sublocality },
            { "sublocality_level_1", ResponsePlaceType.Sublocality_level_1 },
            { "sublocality_level_2", ResponsePlaceType.Sublocality_level_2 },
            { "sublocality_level_3", ResponsePlaceType.Sublocality_level_3 },
            { "sublocality_level_4", ResponsePlaceType.Sublocality_level_4 },
            { "sublocality_level_5", ResponsePlaceType.Sublocality_level_5 },
            { "subpremise", ResponsePlaceType.Subpremise },
            { "town_square", ResponsePlaceType.Town_square },
        };

        public static IReadOnlyDictionary<string, BusinessStatus> BusinessStatusTable = new Dictionary<string, BusinessStatus>
        {
            { "OPERATIONAL", BusinessStatus.Operational },
            { "CLOSED_TEMPORARILY", BusinessStatus.ClosedTemporarily },
            { "CLOSED_PERMANENTLY", BusinessStatus.ClosedPermanently },
        };
    }
}